object Versions {
    const val play_services_auth = "16.0.1"
    const val rxandroid = "2.0.2"
    const val rxjava = "2.2.0"
    const val okhttp = "3.12.1"
    const val rxbinding = "1.0.0"
    const val logging_interceptor = "3.12.1"
    const val retrofit = "2.4.0"
    const val converter_gson = "2.4.0"
    const val rxjava2_adapter = "1.0.0"
    const val gson = "2.8.5"
    const val dagger = "2.15"
    const val dagger_compiler = "2.15"
    const val dagger_android_processor = "2.16"
    const val jsr250_api = "1.0"
    const val multidex = "1.0.3"
    const val circularimageview = "3.2.0"
    const val shimmer = "2.1.0"
    const val junit = "4.12"
    const val glide = "4.9.0"
    const val glide_compiler = "4.9.0"
    const val androidx_core = "1.3.0"
    const val androidx_appcompat = "1.1.0"
    const val androidx_constraintlayout = "1.1.3"
}

object Deps {
    val androidx_core = "androidx.core:core-ktx:${Versions.androidx_core}"
    val androidx_appcompat = "androidx.appcompat:appcompat:${Versions.androidx_appcompat}"
    val androidx_constraintlayout = "androidx.constraintlayout:constraintlayout:${Versions.androidx_constraintlayout}"

    val play_services_auth = "com.google.android.gms:play-services-auth:${Versions.play_services_auth}"
    val rxandroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxandroid}"
    val rxjava = "io.reactivex.rxjava2:rxjava:${Versions.rxjava}"
    val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    val logging_interceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.logging_interceptor}"
    val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    val converter_gson = "com.squareup.retrofit2:converter-gson:${Versions.converter_gson}"
    val rxjava2_adapter = "com.jakewharton.retrofit:retrofit2-rxjava2-adapter:${Versions.rxjava2_adapter}"
    val gson = "com.google.code.gson:gson:${Versions.gson}"
    val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    val dagger_compiler = "com.google.dagger:dagger-compiler:${Versions.dagger_compiler}"
    val dagger_android_processor = "com.google.dagger:dagger-android-processor:${Versions.dagger_android_processor}"
    val jsr250_api = "javax.annotation:jsr250-api:${Versions.jsr250_api}"
    val multidex = "com.android.support:multidex:${Versions.multidex}"
    val circularimageview = "com.mikhaellopez:circularimageview:${Versions.circularimageview}"
    val rxBindingDesign = "com.jakewharton.rxbinding:rxbinding-design:${Versions.rxbinding}"
    val shimmer = "io.supercharge:shimmerlayout:${Versions.shimmer}"
    val junit = "junit:junit:${Versions.junit}"
    val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    val glide_compiler = "com.github.bumptech.glide:compiler:${Versions.glide_compiler}"
}